// <auto-generated />
using System;
using DigitalAwareness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalAwareness.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250824133141_InitialFirst")]
    partial class InitialFirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("ReferralNumberSequence");

            modelBuilder.Entity("DigitalAwareness.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Agra",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Akbarpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aligarh",
                            StateId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amroha",
                            StateId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ayodhya(Faizabad)",
                            StateId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Azamgarh",
                            StateId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Baheraich",
                            StateId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ballia",
                            StateId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Banda",
                            StateId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Baraut",
                            StateId = 1
                        },
                        new
                        {
                            Id = 61,
                            Name = "Bareilly",
                            StateId = 1
                        },
                        new
                        {
                            Id = 62,
                            Name = "BAsti",
                            StateId = 1
                        },
                        new
                        {
                            Id = 63,
                            Name = "Budaun",
                            StateId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bulandshahr",
                            StateId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Chandausi",
                            StateId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Deoria",
                            StateId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Etah",
                            StateId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Etawah",
                            StateId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Farrukhabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Fatehpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Firozabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ghaziabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 20,
                            Name = "Gonda",
                            StateId = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Lucknow",
                            StateId = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Modinagar",
                            StateId = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Mirzapur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Meerut",
                            StateId = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "Maunath Bhajan(Mau)",
                            StateId = 1
                        },
                        new
                        {
                            Id = 26,
                            Name = "Mathura",
                            StateId = 1
                        },
                        new
                        {
                            Id = 27,
                            Name = "Mainpuri",
                            StateId = 1
                        },
                        new
                        {
                            Id = 28,
                            Name = "Lalitpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 29,
                            Name = "Lakhimpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "Khurja",
                            StateId = 1
                        },
                        new
                        {
                            Id = 31,
                            Name = "Khora",
                            StateId = 1
                        },
                        new
                        {
                            Id = 32,
                            Name = "Kanpur Cantonment",
                            StateId = 1
                        },
                        new
                        {
                            Id = 33,
                            Name = "Kanpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 34,
                            Name = "Jhansi",
                            StateId = 1
                        },
                        new
                        {
                            Id = 35,
                            Name = "Jaunpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 36,
                            Name = "Hathras",
                            StateId = 1
                        },
                        new
                        {
                            Id = 37,
                            Name = "Hardoi",
                            StateId = 1
                        },
                        new
                        {
                            Id = 38,
                            Name = "Hapur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 39,
                            Name = "Greater Noida",
                            StateId = 1
                        },
                        new
                        {
                            Id = 40,
                            Name = "Gorakhpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 41,
                            Name = "Moradabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 42,
                            Name = "Muzaffarnagar",
                            StateId = 1
                        },
                        new
                        {
                            Id = 43,
                            Name = "Noida",
                            StateId = 1
                        },
                        new
                        {
                            Id = 44,
                            Name = "Orai",
                            StateId = 1
                        },
                        new
                        {
                            Id = 45,
                            Name = "Pilibhit",
                            StateId = 1
                        },
                        new
                        {
                            Id = 46,
                            Name = "Prayagraj(Allahabad)",
                            StateId = 1
                        },
                        new
                        {
                            Id = 47,
                            Name = "Raebareli",
                            StateId = 1
                        },
                        new
                        {
                            Id = 48,
                            Name = "Rampur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 49,
                            Name = "Saharanpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 50,
                            Name = "Sambhal",
                            StateId = 1
                        },
                        new
                        {
                            Id = 51,
                            Name = "Vrindavan",
                            StateId = 1
                        },
                        new
                        {
                            Id = 52,
                            Name = "Unnao",
                            StateId = 1
                        },
                        new
                        {
                            Id = 53,
                            Name = "Sultanpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 54,
                            Name = "Varanasi",
                            StateId = 1
                        },
                        new
                        {
                            Id = 55,
                            Name = "Sitapur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 56,
                            Name = "Shikohabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 57,
                            Name = "Shamli",
                            StateId = 1
                        },
                        new
                        {
                            Id = 58,
                            Name = "Shahjahanpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 59,
                            Name = "Sarnath",
                            StateId = 1
                        },
                        new
                        {
                            Id = 60,
                            Name = "Sambhal",
                            StateId = 1
                        },
                        new
                        {
                            Id = 64,
                            Name = "Mumbai",
                            StateId = 2
                        },
                        new
                        {
                            Id = 65,
                            Name = "Pune",
                            StateId = 2
                        },
                        new
                        {
                            Id = 66,
                            Name = "Nagpur",
                            StateId = 2
                        },
                        new
                        {
                            Id = 67,
                            Name = "Nashik",
                            StateId = 2
                        },
                        new
                        {
                            Id = 68,
                            Name = "Aurangabad",
                            StateId = 2
                        },
                        new
                        {
                            Id = 69,
                            Name = "New Delhi",
                            StateId = 3
                        },
                        new
                        {
                            Id = 70,
                            Name = "Delhi Cantonment",
                            StateId = 3
                        },
                        new
                        {
                            Id = 71,
                            Name = "Bangalore",
                            StateId = 4
                        },
                        new
                        {
                            Id = 72,
                            Name = "Mysore",
                            StateId = 4
                        },
                        new
                        {
                            Id = 73,
                            Name = "Mangalore",
                            StateId = 4
                        },
                        new
                        {
                            Id = 74,
                            Name = "Kolkata",
                            StateId = 5
                        },
                        new
                        {
                            Id = 75,
                            Name = "Howrah",
                            StateId = 5
                        },
                        new
                        {
                            Id = 76,
                            Name = "Durgapur",
                            StateId = 5
                        });
                });

            modelBuilder.Entity("DigitalAwareness.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maharashtra"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delhi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Karnataka"
                        },
                        new
                        {
                            Id = 5,
                            Name = "West Bengal"
                        });
                });

            modelBuilder.Entity("DigitalAwareness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferralNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR ReferralNumberSequence");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalAwareness.Models.City", b =>
                {
                    b.HasOne("DigitalAwareness.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("DigitalAwareness.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
