// <auto-generated />
using System;
using DigitalAwareness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalAwareness.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250822185831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("ReferralNumberSequence");

            modelBuilder.Entity("DigitalAwareness.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lucknow",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kanpur",
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Agra",
                            StateId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Varanasi",
                            StateId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Meerut",
                            StateId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Allahabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bareilly",
                            StateId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ghaziabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Noida",
                            StateId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Faizabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mumbai",
                            StateId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pune",
                            StateId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Nagpur",
                            StateId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Nashik",
                            StateId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Aurangabad",
                            StateId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "New Delhi",
                            StateId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Delhi Cantonment",
                            StateId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bangalore",
                            StateId = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "Mysore",
                            StateId = 4
                        },
                        new
                        {
                            Id = 20,
                            Name = "Mangalore",
                            StateId = 4
                        },
                        new
                        {
                            Id = 21,
                            Name = "Kolkata",
                            StateId = 5
                        },
                        new
                        {
                            Id = 22,
                            Name = "Howrah",
                            StateId = 5
                        },
                        new
                        {
                            Id = 23,
                            Name = "Durgapur",
                            StateId = 5
                        });
                });

            modelBuilder.Entity("DigitalAwareness.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uttar Pradesh"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maharashtra"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delhi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Karnataka"
                        },
                        new
                        {
                            Id = 5,
                            Name = "West Bengal"
                        });
                });

            modelBuilder.Entity("DigitalAwareness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferralNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR ReferralNumberSequence");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalAwareness.Models.City", b =>
                {
                    b.HasOne("DigitalAwareness.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("DigitalAwareness.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
